- ide-common/src/main/java/org/digma/intellij/plugin/insights/view/BuildersHolder.java
- model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/CodeObjectInsight.kt
- model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanFlow.kt
- model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanUsagesInsight.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsListCellRenderer.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanPanels.kt
> Feature/Adjust span usage insight - plus link 2 jaeger trace

- ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/ToolWindowTabsHelper.kt
- src/main/java/org/digma/intellij/plugin/service/ErrorsActionsService.java
if error details in on and switching to summary tab the error details is not closed and the links on summary tab are un usable.
this PR closes the error details when switching to summary tab.
> close-error-details-when-switching-to-summary-tab

- src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/DurationBreakdownPanel.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/DurationPanel.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsListCellRenderer.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanPanels.kt
New look of DurationBreakdown:
**For now implementation has hardcoded limitation to 30 characters.**
If you have any ideas how to hide string text dynamically - please tell me your advices and tips ;)
`    if (fullDisplayName.length > 30) {
limitedDisplayName = fullDisplayName.trim().take(30) + "..."
}`
For now I decided not to waste so much time on this fix to make it to be hidden dynamically according to user's change of panel width
> set limitation of text displaying for durationBreakdown insight (#203)

- rider/Digma.Rider.Plugin/Digma.Rider/Highlighting/CodeLensProviderFactory.cs
- rider/Digma.Rider.Plugin/Digma.Rider/Highlighting/CodeObjectsHighlighter.cs
Fix is ready I added return of null from GetProvider and skip the code lens on case if all 5 available providers are used already.
please check it before the final merging into main.
Manual testing was successful.
> Fix logic for CodeObjectsHighlighter #227

- src/main/resources/META-INF/plugin.xml
Disabled displaying of popups.
New items to NOTIFICATIONS sections are being added without any issues:
> IntelliJ plugin should not use popup notifications #204

- src/main/kotlin/org/digma/intellij/plugin/ui/common/EnvironmentsPanel.kt
Fixes #278 
Used _SwingUtilities.invokeLater_ instead of _ApplicationManager.getApplication().invokeLater_ as last one provides duplication problem
> #278 Fix EnvironmentsPanel duplication

- ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoService.java
- src/main/kotlin/org/digma/intellij/plugin/ui/common/EnvironmentsDropdownPanel.kt
Fixes #311 
After investigation of logs from Shay's machine I figured out that root cause of this problem was `DocumentInfoService`:
`    private final Map<String, DocumentInfoContainer> documents = Collections.synchronizedMap(new HashMap<>());`
The thread calling the `removeDocumentInfo` method was blocked waiting to acquire the lock of the `synchronized` map.
To improve this, I used a concurrent map implementation (`ConcurrentHashMap`) instead of a `synchronized` map. This will allow multiple threads to access the map concurrently without blocking each other.
By using `ConcurrentHashMap`, we can avoid blocking the UI thread and improve the concurrency of our application.
> Fixed Rider is not responding #311

- model/src/main/kotlin/org/digma/intellij/plugin/model/rest/recentactivity/RecentActivityResult.kt
this is related to colorized insight icon in recent activity, please note that importance equals 0 means that the backend is not updated yet.
so in such case, we can have no colored icons as today
goes together with backend PR https://github.com/digma-ai/digma-collector-backend/pull/833
> add importance to SlimAggregatedInsight

- src/main/java/org/digma/intellij/plugin/service/EditorService.java
- src/main/kotlin/org/digma/intellij/plugin/ui/common/UpdateVersionPanel.kt
fixes #627 
the fix : the entire directory has `deleteOnExit = true` - so no need for each file separately.
also added feature that those guides are open in ReadOnly mode.
> Bugfix/temp guide files - delete on exit - based on entire folder

- ide-common/src/main/java/org/digma/intellij/plugin/common/DebugUtilDontCommit.java
- ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoService.java
- ide-common/src/main/java/org/digma/intellij/plugin/editor/CurrentContextUpdater.java
- ide-common/src/main/java/org/digma/intellij/plugin/editor/EditorEventsHandler.java
- ide-common/src/main/java/org/digma/intellij/plugin/ui/MainToolWindowCardsController.java
- ide-common/src/main/kotlin/org/digma/intellij/plugin/insights/AbstractInsightsProvider.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/insights/CodeLessSpanInsightsProvider.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/ErrorsViewService.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/InsightsViewService.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/SummaryViewService.kt
- model/src/main/kotlin/org/digma/intellij/plugin/model/discovery/CodeLessSpan.kt
- model/src/main/kotlin/org/digma/intellij/plugin/ui/model/PanelModel.kt
- model/src/main/kotlin/org/digma/intellij/plugin/ui/model/Scopes.kt
- model/src/main/kotlin/org/digma/intellij/plugin/ui/model/errors/ErrorsModel.kt
- model/src/main/kotlin/org/digma/intellij/plugin/ui/model/insights/InsightsModel.kt
- src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIService.java
- src/main/java/org/digma/intellij/plugin/service/ErrorsActionsService.java
- src/main/java/org/digma/intellij/plugin/toolwindow/recentactivity/DigmaBottomToolWindowFactory.java
- src/main/kotlin/org/digma/intellij/plugin/navigation/codeless/CodelessNavigation.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/common/InstallationWizardSidePanelWindowPanel.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/common/ScopeLineIconProducer.kt
- src/main/resources/META-INF/org.digma.intellij-with-intellij-platform.xml
- src/main/resources/webview/jaegerui/index.html
- src/main/resources/webview/jaegerui/jaegeruitemplate.ftl
first phase navigation , show insights for non-discoverable span. supports a request for go-to-span from jaeger ui and recent activity.
currently there is no refresh for the insights.
there is one issue:
if the cursor is inside a method body and the insights are shown in the insights window. click a non discoverable span in recent activity, the insights for the span are shown. when click the method again  the view is not replaced until you click somewhere outside the latest method. how do we want that to behave? replace the view again on first click in the method?
[Screencast from 2023-05-21 22-59-04.webm](https://github.com/digma-ai/digma-intellij-plugin/assets/170266/be31ad4d-c630-440a-92eb-1dd980b8f6ee)
> First phase navigation change issue 677

- model/src/main/kotlin/org/digma/intellij/plugin/model/lens/CodeLens.kt
fixes #725 
add codeObjectId to equals and hashCode
> Bugfix/CodeLens uniqueness - add codeObjectId

- src/main/kotlin/org/digma/intellij/plugin/ui/common/CopyableLabel.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/errors/ErrorDetailsPanel.kt
This is voodo, i don't understand why it started happening , nothing changed in copyable label but suddenly the error details name is not showing. when i remove border=null from copyable label its ok again. I have no idea why, it works for the past year and suddenly not. other places using CopyableLabel work with no issues.
an alternative to CopyableLabel can be JBLabel with setCopyable(true) and isAllowAutoWrapping = true , but for some reason tooltip is not working in JBLabel.
> fix error details name label not showing

- analytics-provider/src/test/java/org/digma/intellij/plugin/analytics/InsightsTests.java
- model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SlowEndpointInsight.kt
Part of https://github.com/digma-ai/digma-collector-backend/issues/970
> Cleanup obsolete props in `SlowEndpointInsight`

- ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java
- ide-common/src/main/java/org/digma/intellij/plugin/analytics/Environment.java
- ide-common/src/main/java/org/digma/intellij/plugin/refreshInsightsTask/RefreshService.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/analytics/BackendConnectionUtil.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/analytics/EnvironmentRefreshScheduler.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/codelens/AbstractCodeLensService.kt
- model/src/main/kotlin/org/digma/intellij/plugin/ui/model/environment/EnvironmentsSupplier.kt
there are few triggers for environment refresh:
a scheduler that triggers every 10 seconds, its the default and can be changed from settings.
when calling BackendConnectionUtil.testConnectionToBackend.
when the cursor moves between methods.
Something to consider:
we now have a few schedulers in the plugin, each occupies a thread and resources:
environment refresh,
insights refresh,
recent activity refresh,
live view refresh,
we can probably merge the login into one scheduler
> Fix environment refresh

- java/src/main/kotlin/org/digma/intellij/plugin/idea/deps/ModulesDepsService.kt
- java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt
relates to issue #859 .
relates to PR #934 and backend PR https://github.com/digma-ai/otel-java-instrumentation/pull/26
adding extra dependency to digma 
`implementation 'io.github.digma-ai:digma-spring-boot-micrometer-tracing-autoconf:0.7.2'`
> Feature/add dep of Digma Spring Boot Micrometer Autoconf

- java/src/main/kotlin/org/digma/intellij/plugin/idea/deps/ModulesDepsService.kt
- java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt
- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt
Roni's notes:
```
1. We are using the wrong system property for OTLP endpoint
2. We need to address the fact that the default is HTTP and not GRPC
3. The client-side discovery is not working for the navigation
4. We need to remove the version numbers from the dependencies
5. We might be missing aop?
```
this PR addresses
1. using the right entry name `management.otlp.tracing.endpoint`
2. we use OtlpGrpcSpanExporter by [digma 0.7.4](https://github.com/digma-ai/otel-java-instrumentation/pull/27)
3. could not see the problem
4. will be handled in different PR
5. yes added `spring-boot-starter-aop`
> Fixes/SpringBootMicrometer - OTLP GRPC 

- src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIService.java
the jaeger links to spans stopped working if span doesn't have method code object id related to it.
it happens since PR #744 
seems like we took the RAW spanID (which is used for neto jaeger), 
instead of spanCodeObjectId
> Bug fix/jaeger links to spans

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/digma-base.gradle.kts
- ide-common/src/main/java/org/digma/intellij/plugin/common/Retries.java
- java/build.gradle.kts
- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt
- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OTELJarProvider.kt
- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OTELJarProviderStartup.kt
- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/constants.kt
- src/main/resources/META-INF/org.digma.intellij-with-java.xml
This PR changes the way otel jars are downloaded:
the two jars are downloaded on every gradle build and packaged in the plugin zip in the java module jar under a directory otelJars.
that means internet connection is necessary when building. to use gradle offline do not clean. after gradle clean a connection is necessary.
when the IDE starts, the two jars are unpacked to /tmp/digma-otel-jars or whatever is the temp directory on the machine as returned by System.getProperty("java.io.tmpdir").
after unpacking the jars are ready for use.
after unpacking the jars, a background thread will attempt to download the latest jars from github, if succeeds it will override the files in /tmp/digma-otel-jars
the jars are never deleted by the plugin and are there as long as the IDE is up. they are …
> Otel agent jars

- ide-common/build.gradle.kts
- ide-common/src/main/kotlin/org/digma/intellij/plugin/docker/DockerService.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/docker/Downloader.kt
- ide-common/src/main/kotlin/org/digma/intellij/plugin/docker/Engine.kt
This PR changed the way docker compose file is downloaded. and makes sure the file is available even if there is no internet connection.
the file is packaged on every build into the jar ide-common in folder docker-compose.
on startup, if local engine is installed the file is unpacked to /tmp/digma-docker or whatever is the temp directory on the machine as returned by System.getProperty("java.io.tmpdir").
after unpacking, the file is ready for use.
after unpacking , a background thread will attempt to download the latest file, if succeeds it will override the file in /tmp/digma-docker. if the download fails the unpacked file is untouched and available for use. 
if local engine is not installed the file will not be unpacked.
on DockerService.installEngine if the file does not exists in …
> Package compose file for offline

- java/build.gradle.kts
- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OTELJarProvider.kt
seems like [OTEL Agent version 1.30.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.30.0) creates some regression to our Java extension, and method (code object) of Spring Endpoints are not being recorded as usual
> Bug fix/downloading OTEL agent version 1.29.0 instead of latest

- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/QuarkusRunConfigurationWrapper.kt
reduce the batching size and timeout so traces would manage to go out.
addresses issue #1338 - Summary A.
based on [quarkus guide](https://quarkus.io/guides/opentelemetry#quarkus-opentelemetry_quarkus.otel.bsp.max.queue.size)
seeing it solves the problem for quarkus version **3.2.6** 
in version 2.16 cannot affect those params
and in version 3.4.1 seeing some problem (see [details in a dedicated comment](https://github.com/digma-ai/digma-intellij-plugin/pull/1341#issuecomment-1742701500))
1. go to git repo:
https://github.com/quarkusio/quarkus-quickstarts/tree/main/opentelemetry-quickstart
2. run test class (annotated with **QuarkusTest** )
https://github.com/quarkusio/quarkus-quickstarts/blob/main/opentelemetry-quickstart/src/test/java/org/acme/opentelemetry/TracedResourceTest.java
> Feature/QuarkusTests - configure tests to reduce batching impact

- java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt
- src/main/kotlin/org/digma/intellij/plugin/ui/recentactivity/AddEnvironmentsService.kt
fixes #1456 .
relying on auto conf PR
https://github.com/digma-ai/otel-java-instrumentation/pull/32
which allow setting `MANAGEMENT_OPENTELEMETRY_RESOURCE-ATTRIBUTES` cross spring boot versions 3.0.x 3.1.x and 3.2.x
the JAR is `digma-spring-boot-micrometer-tracing-autoconf` is at version 0.7.7
> Feature/spring boot micrometer tracing - support add env

- java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt
fixes #1481
support maven goal `jetty:run` via RunConfig and via maven plugin
> Feature/Support jetty:run as maven plugin

- model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanFlow.kt
- model/src/main/kotlin/org/digma/intellij/plugin/model/rest/recentactivity/RecentActivityResult.kt
part of PR https://github.com/digma-ai/digma-collector-backend/pull/1442/files
found out that `methodCodeObjectId` should be nullable instead of possible empty string
> Bug fix/methodCodeObjectId is nullable

- ide-common/src/main/kotlin/org/digma/intellij/plugin/vcs/VcsService.kt
Expected behavior: also support HTTP links
> Fixed bug where only git@github.com links were supported

- build.gradle.kts
- buildSrc/src/main/kotlin/common-java.gradle.kts
- buildSrc/src/main/kotlin/common-kotlin.gradle.kts
this PR solves this issue
https://github.com/JetBrains/gradle-intellij-plugin/issues/1538
and these
//todo: this is a workaround for these issues:
// 241 should run with JBR 21. but currently there is a bug in gradle-intellij-plugin that downloads
// a 21 JBR without jcef support.
// see this issue:
// https://github.com/JetBrains/gradle-intellij-plugin/issues/1534
// and this PR fixes it
// https://github.com/JetBrains/gradle-intellij-plugin/pull/1535
// when gradle-intellij-plugin has a new release including the above fix it will download the right 21 JBR.
// but then there is this issue:
// https://github.com/digma-ai/digma-intellij-plugin/issues/1734
// if 241 runs with 21 then gradle-intellij-plugin will configure the test task to use this JBR,
// but some of our tests fail with 21. …
> dont use jetbrains vendor in toolchain

- build.gradle.kts
- ide-common/src/main/java/org/digma/intellij/plugin/settings/ProjectSettings.java
- ide-common/src/main/java/org/digma/intellij/plugin/settings/SettingsComponent.java
- ide-common/src/main/java/org/digma/intellij/plugin/settings/SettingsState.java
- ide-common/src/main/kotlin/org/digma/intellij/plugin/posthog/SettingsChangeTracker.kt
- jvm-common/build.gradle.kts
- jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/execution/JavaParametersMerger.kt
- jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/execution/JavaToolOptionsBuilder.kt
- jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/execution/OTELJarProvider.kt
- jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/execution/OtelAgentPathProvider.kt
- jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/execution/constants.kt
- jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/execution/flavor/DefaultInstrumentationFlavor.kt
- jvm-common/src/main/resources/jars-urls.properties
new way to do extended instrumentation using a java agent that injects @WithSpan annotations to methods instead of instrumentation the standard way with otel extension module.
digma-agent configuration
https://github.com/digma-ai/digma-agent/blob/4ff6e7a9fe3d2a32e827a0a8bfff380c6865a6d7/src/main/java/org/digma/Configuration.java
> extended-observability-experiment
