digma-ai/digma-intellij-plugin

rider/Digma.Rider.Plugin/Digma.Rider/Highlighting/DaemonReanalyze.cs
rider/Digma.Rider.Plugin/Digma.Rider/Protocol/CodeObjectsHost.cs

Signed-off-by: shalom <shalom938@gmail.com>

a more correct way to reanalyze documents

---

rider/Digma.Rider.Plugin/Digma.Rider/Highlighting/CodeObjectsHighlighter.cs
rider/Digma.Rider.Plugin/Digma.Rider/Highlighting/Icons.cs
rider/src/main/resources/icons/exclMark.svg

Signed-off-by: shalom <shalom938@gmail.com>

add icon to error hotspot

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java
ide-common/src/main/java/org/digma/intellij/plugin/notifications/NotificationUtil.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/AbstractViewService.kt

Signed-off-by: shalom <shalom938@gmail.com>

fix analytics error handling

---

ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoContainer.java
ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoService.java
ide-common/src/main/java/org/digma/intellij/plugin/insights/InsightsProvider.java
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaCodeLensService.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/discovery/MethodInfo.kt
rider/Digma.Rider.Plugin/Digma.Rider/Highlighting/CodeObjectsHighlighter.cs

In scope of this PR was done:
* getAllInsights from the cache
* remove duplicated importance icon for Java code
* fix null issue when loading the insights list and DB connection was lost

Feature/get insights from the cache (#220)

---

src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsListCellRenderer.kt

Fix displaying of Endpoint groups #233

---

ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoContainer.java

getAllInsights must not return null #240

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/GrpcFramework.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt

similar to #235 just for vanilla GRPC framework

Feature/GRPC Server vanilla - endpoints discovery

---

src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/DurationPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanPanels.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/UsagesPanel.kt

Fix 'Top usage' and 'Durations' insights layouts #242

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/EnvironmentsPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsCommon.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsListCellRenderer.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/summaries/SummaryPanelListCellRenderer.kt

Remove empty space after envs list row #244

---

src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/DurationBreakdownPanel.kt

#241 set limitation of duration breakdown items dynamically

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageUtils.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JaxrsFramework.java
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaPsiUtils.kt

Feature/JAX-RS - refer to class and method hierarchies when searching for annotations

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/editor/FocusedDocumentHelper.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/editor/GeneralFileEditorListener.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/editor/PaginationUtil.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/DurationBreakdownPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/PaginationPanel.kt

Fixed pagination issue for DurationBreakdown insight

Fix pagination for DurationBreakdownInsight

---

ide-common/src/main/java/org/digma/intellij/plugin/insights/view/GroupListViewItemBuilder.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/editor/PaginationUtil.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/DurationBreakdownPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/EPNPlusSpansPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsCommon.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsListCellRenderer.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/PaginationPanel.kt

Implemented links and pagination for N+1 Endpoint insight:

Implement links and pagination for N+1 endpoint insight

---

ide-common/src/main/java/org/digma/intellij/plugin/insights/view/BuildersHolder.java
model/src/main/kotlin/org/digma/intellij/plugin/model/model.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/CodeObjectInsight.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanNPlusEndpoints.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanNPlusOneInsight.kt
model/src/main/kotlin/org/digma/intellij/plugin/ui/model/insights/InsightListViewItem.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/EPNPlusSpansPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsCommon.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsListCellRenderer.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanNPlusOneInsightPanel.kt

Fixes #282 - implemented N+1 insight for spans 
(endpoint N+1 insight was implemented in scope of previous PR: https://github.com/digma-ai/digma-intellij-plugin/pull/302)

#282 Implement N+1 Span insight for the Internal Span

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaCodeLensProviderFactory.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaCodeLensService.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/JavaCodeVisionProvider.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider1.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider10.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider2.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider3.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider4.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider5.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider6.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider7.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider8.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/CodeLensMethodInsightsProvider9.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/ErrorHotspotCodeLensProvider.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/HighUsageCodeLensProvider.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/LowUsageCodeLensProvider.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/ScaleFactorCodeLensProvider.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/codeLensProviders/SlowEndpointCodeLensProvider.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsCommon.kt
src/main/resources/META-INF/org.digma.intellij-with-java.xml

Bug/jetbrains plugin does not display more than one code lens #310

---

build.gradle.kts
src/main/java/org/digma/intellij/plugin/toolwindow/CustomResourceHandler.kt
src/main/java/org/digma/intellij/plugin/toolwindow/CustomResourceHandlerUtil.kt
src/main/java/org/digma/intellij/plugin/toolwindow/DigmaBottomToolWindowFactory.java
src/main/java/org/digma/intellij/plugin/toolwindow/JBCefBrowserUtil.java
src/main/java/org/digma/intellij/plugin/toolwindow/ThemeChangeListener.java
src/main/java/org/digma/intellij/plugin/toolwindow/ThemeUtil.java
src/main/java/org/digma/intellij/plugin/toolwindow/ToolWindowUtil.java
src/main/java/org/digma/intellij/plugin/toolwindow/UIThemeRequest.kt
src/main/java/org/digma/intellij/plugin/toolwindow/UiTheme.java
src/main/java/org/digma/intellij/plugin/toolwindow/UiThemePayload.kt
src/main/resources/webview/indextemplate.ftl

#333 Dynamically change UI themes for Recent Activity

---

ide-common/src/main/java/org/digma/intellij/plugin/common/IDEUtilsService.java
ide-common/src/main/java/org/digma/intellij/plugin/persistence/PersistenceService.java
java/build.gradle.kts
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationExtension.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OTELJarProvider.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OTELJarProviderStartup.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/constants.kt
model/src/main/kotlin/org/digma/intellij/plugin/persistence/PersistenceData.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/NavigationPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/SettingsHintPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/SwitchButton.kt
src/main/resources/META-INF/org.digma.intellij-with-java.xml
src/main/resources/META-INF/plugin.xml

addresses issue #306 .
affects the Run Configuration

quick instrumentation java code

---

ide-common/src/main/java/org/digma/intellij/plugin/settings/ProjectSettings.java
ide-common/src/main/java/org/digma/intellij/plugin/settings/SettingsComponent.java
ide-common/src/main/java/org/digma/intellij/plugin/settings/SettingsState.java
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationExtension.kt

Feature/setting for Runtime Observability Backend (exporter)

---

ide-common/src/main/java/org/digma/intellij/plugin/insights/view/InsightsViewBuilder.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/InsightsViewService.kt
model/src/main/kotlin/org/digma/intellij/plugin/ui/model/insights/InsightsModel.kt
model/src/main/kotlin/org/digma/intellij/plugin/ui/model/insights/NoObservability.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/Laf.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/Panels.kt
src/main/kotlin/org/digma/intellij/plugin/ui/insights/InsightsTab.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsCommon.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsListCellRenderer.kt

addresses partially to issue #382
creating the panels plus display them with the right conditions.
**Note:** No buttons yet (display nor functionality)

Feature/Panels for No Observability

---

ide-common/src/main/java/org/digma/intellij/plugin/refreshInsightsTask/RefreshService.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/analytics/BackendConnectionMonitor.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/analytics/BackendConnectionUtil.kt
src/main/java/org/digma/intellij/plugin/service/EditorInteractionService.java
src/main/resources/META-INF/plugin.xml

Fixed backend connection monitor (#406)

---

src/main/java/org/digma/intellij/plugin/toolwindow/recentactivity/DigmaBottomToolWindowFactory.java

add null check while getting environments

---

src/main/kotlin/org/digma/intellij/plugin/ui/list/PanelList.kt

Right now if codeobject has any insight with broken data then we dont show anything at all.

Add error handling and analytics for broken insights

---

model/src/main/kotlin/org/digma/intellij/plugin/ui/model/insights/InsightsModel.kt

Bugfix/Initial state is not unknown (#433)

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/Environment.java
ide-common/src/main/java/org/digma/intellij/plugin/settings/SettingsState.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/editor/GeneralFileEditorListener.kt

Refresh env list if it is empty on RecentAct call

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/NavigationPanel.kt

Fix app trying to update nav panel on disposed project instance

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java

Add null check during onInsightReceived

---

ide-common/src/main/java/org/digma/intellij/plugin/document/CodeLensProvider.java
src/main/resources/webview/installationwizard/index.js
src/main/resources/webview/recentactivity/index.js

Fixed CodeLens displaying for Java project #455

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/InsightsViewService.kt

Fix showing 'Loading...' when digma has no envs yet

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/EnvironmentsDropdownPanel.kt

Bug fix/range check

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java

Bug fix/avoid nulls and instead return empty list

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java

Bug fix/handle possible null methodId

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/posthog/ActivityMonitor.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/SettingsHintPanel.kt

Add analytics for the 'observablity' toggle button in IntelliJ

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationExtension.kt

Bug fix/do not override OTEL service name if already defined

---

ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoService.java
ide-common/src/main/java/org/digma/intellij/plugin/refreshInsightsTask/RefreshService.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/editor/GeneralFileEditorListener.kt

this PR will help addressing issue #474.
also it address bug fix, so whenever scope is not method, and button refresh is clicked, then it enters a state where no longer respecting the refresh button

Feature/refresh refactoring - refresh file even if scope is not method

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java
ide-common/src/main/java/org/digma/intellij/plugin/insights/InsightsProvider.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/InsightsViewService.kt

Bugfix/plugin exceptions#407

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/EnvironmentsDropdownPanel.kt

Disable env icon if current method does not have insights #420

---

src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/EPNPlusSpansPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/PaginationPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/ScalingRootCausePanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/UsagesPanel.kt

Add pagination to TopUsage panel

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java

Fixed usageStatus must not be null #508

---

ide-common/src/main/java/org/digma/intellij/plugin/document/CodeLensProvider.java

Add `Never Reached` code lens for code objects with no data

---

ide-common/src/main/java/org/digma/intellij/plugin/document/CodeLensProvider.java

Show `Runtime data` on any method if we have any non-critical insights

---

ide-common/src/main/java/org/digma/intellij/plugin/document/CodeLensProvider.java

Show `Not Reached` only for instrumented endpoints/spans

---

analytics-provider/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsProvider.java
analytics-provider/src/main/java/org/digma/intellij/plugin/analytics/RestAnalyticsProvider.java
analytics-provider/src/test/java/org/digma/intellij/plugin/analytics/InsightsTests.java
ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java
ide-common/src/main/java/org/digma/intellij/plugin/document/CodeLensProvider.java
ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoContainer.java
ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoService.java
ide-common/src/main/java/org/digma/intellij/plugin/refreshInsightsTask/RefreshService.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/ErrorsViewService.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/InsightsViewService.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/discovery/MethodInfo.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/InsightsOfMethodsRequest.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/InsightsOfMethodsResponse.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/MethodWithInsights.kt

Feature/use new API to get insights - per method

---

analytics-provider/build.gradle.kts
analytics-provider/src/test/java/org/digma/intellij/plugin/analytics/InsightsTests.java
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/AffectedEndpointInfo.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanInfo.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanScalingRootCauseInsight.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/ScalingRootCausePanel.kt

Add `Trace` button to `Scaling Issue Root Cause` insight

---

ide-common/src/main/java/org/digma/intellij/plugin/document/CodeLensProvider.java
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/CodeObjectInsight.kt

Bugfix/code lense - using methodId and simpler code

---

model/src/main/kotlin/org/digma/intellij/plugin/model/rest/version/VersionResponse.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/UpdateVersionPanel.kt
src/main/resources/guides/upgrade_helm.md

Feature/update backend - guide for helm

---

ide-common/src/main/java/org/digma/intellij/plugin/document/DocumentInfoContainer.java

https://github.com/digma-ai/digma-intellij-plugin/issues/625

filter out unmap insights related to

---

src/main/resources/webview/recentactivity/indextemplate.ftl

Update "dig with digma" link in Recent activity

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageUtils.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/SpringBootFramework.java

Bugfix/discovery spring web - possible array of paths

---

ide-common/src/main/java/org/digma/intellij/plugin/common/JBCefBrowserBuilderCreator.java
src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIFileEditor.java
src/main/java/org/digma/intellij/plugin/toolwindow/common/CustomViewerWindow.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/NavigationPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/SettingsHintPanel.kt

show setting menu for all languages
fixes #644

hide observe context menu item

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/posthog/ActivityMonitor.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationExtension.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/RunConfigType.kt

fixes #688.
seeing data captured in Posthog:
Entries:
* Event name: `run config`
* Property `run.config.type` with possible values: GradleRun , MavenRun , JavaRun
* Property `observability.enabled` - boolean

Feature/report run config to Posthog

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java

Bugfix/overcome IndexNotReadyException by using inSmartMode

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationExtension.kt

fixes #710 .
took most of code from PR #479 
seeing the fix happening, now service name of client tester being respected (named **ClientTesterOfPetClinic**):

Bug fix/keep OTEL service name if already defined

---

src/main/java/org/digma/intellij/plugin/service/EditorService.java
src/main/kotlin/org/digma/intellij/plugin/ui/common/UpdateVersionPanel.kt

change loading of update guides

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationExtension.kt

refix of #710 - since for gradle need to do different check
for gradle run, it won't feel the JavaParameters (see issue https://youtrack.jetbrains.com/issue/IDEA-317118)
so reading the settings instead.

Bugfix/When RunConfig gradle check settings for service name

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/NavigationPanel.kt

this PR adds dispose to ScopeLineResultPanel

dispose message bus connection of ScopeLineResultPanel

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/Environment.java
ide-common/src/main/java/org/digma/intellij/plugin/analytics/EnvironmentChanged.java
ide-common/src/main/java/org/digma/intellij/plugin/psi/LanguageService.java
ide-common/src/main/java/org/digma/intellij/plugin/psi/NoOpLanguageService.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/SummaryViewService.kt
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java
model/src/main/kotlin/org/digma/intellij/plugin/ui/model/environment/EnvironmentsSupplier.kt
python/src/main/java/org/digma/intellij/plugin/psi/python/PythonLanguageService.java
rider/src/main/java/org/digma/intellij/plugin/rider/psi/csharp/CSharpLanguageService.java
src/main/java/org/digma/intellij/plugin/emvironment/EnvironmentChangeHandler.java
src/main/java/org/digma/intellij/plugin/toolwindow/recentactivity/DigmaBottomToolWindowFactory.java
src/main/kotlin/org/digma/intellij/plugin/ui/common/EnvironmentsDropdownPanel.kt

update the environment when showing codeless spans, new navigation

---

ide-common/src/main/java/org/digma/intellij/plugin/psi/LanguageService.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java
java/src/main/kotlin/org/digma/intellij/plugin/idea/build/BuildSystemChecker.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/build/JavaBuildSystem.kt
model/src/main/kotlin/org/digma/intellij/plugin/ui/model/insights/NoObservability.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/Consts.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/HtmlUtil.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/Laf.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/MethodInstrumentationPresenter.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/OtelDependencyButton.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/statuspanels/NoObservabilityPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsCommon.kt

Feature/Button to add Otel Dependency

---

src/main/resources/webview/jaegerui/index.html
src/main/resources/webview/jaegerui/jaegeruitemplate.ftl

relates to #748  
and https://github.com/digma-ai/jaeger-ui/issues/16

Update Jaeger UI

---

ide-common/src/main/java/org/digma/intellij/plugin/document/CodeObjectsUtil.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/navigation/codenavigation/CodeNavigator.kt
src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIService.java
src/main/java/org/digma/intellij/plugin/jaegerui/model/incoming/Span.java
src/main/kotlin/org/digma/intellij/plugin/navigation/codeless/CodelessNavigation.kt

Feature/embedded jaeger - using new fields of span and code object ids

---

src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/UsagesPanel.kt

fixes #777 
part of the fix, now seeing span names even if not linkable

Bugfix/Top Usage display span name even if not linkable

---

analytics-provider/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsProvider.java
ide-common/src/main/java/org/digma/intellij/plugin/ui/MainToolWindowCardsController.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/InsightsViewService.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/discovery/CodeLessSpan.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/EndpointInfo.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/RootCauseSpan.kt
model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanFlow.kt
model/src/main/kotlin/org/digma/intellij/plugin/ui/model/Scopes.kt
src/main/java/org/digma/intellij/plugin/jaegerui/JaegerUIService.java
src/main/java/org/digma/intellij/plugin/toolwindow/recentactivity/DigmaBottomToolWindowFactory.java
src/main/kotlin/org/digma/intellij/plugin/navigation/codeless/CodelessNavigation.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/CodeNavigationButton.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/PanelUtil.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/DurationBreakdownPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/EPNPlusSpansPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SlowestSpansPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanNPlusOneInsightPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanPanelsUtil.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanScalingPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/UsagesPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/summaries/SummaryPanelListCellRenderer.kt

This reverts commit cf5bb648224a78086f7eb88e8723fbf896ae2eef.

Revert "change-span-links-to-open-codeless-span (#788)"

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/TabsPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/ErrorsPanel.kt

add tab changed events and error click

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/posthog/ActivityMonitor.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/posthog/ContainerEngineStartupActivity.kt
src/main/resources/META-INF/plugin.xml

adding new key named "user.container-engine" which might contain one of:
"docker"
"podman"
"unknown"

Discover+Notify container engine

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/RunCfgTools.kt

mainly need to handle gradle tasks - main and test
relates to issue #859 - since need to know to Module - by module need to know if it is SpringBoot one

Feature/resolve module from RunConfig

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt

bug fix/using timing prod values

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java

Bug fix/refer to module scope

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationExtension.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/QuarkusRunConfigurationExtension.kt

Small bug fix/print only if backend is ok

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/Constants.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java
java/src/main/kotlin/org/digma/intellij/plugin/idea/deps/ModulesDepsService.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/psi/java/MicrometerTracingFramework.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/Consts.kt
src/main/kotlin/org/digma/intellij/plugin/ui/common/statuspanels/NoObservabilityPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/InsightsCommon.kt

for spring-boot-micrometer-tracing module - need to add annotation of `Observed` instead of `WithSpan`
part of issue #859 SubTask 6
here's the `Observed` FQN 
io.micrometer.observation.annotation.Observed

Feature/add annotation Observed for spring boot micrometer instead of WithSpan

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/deps/ModulesDepsService.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/IRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OtelRunConfigurationExtension.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/QuarkusRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/RunCfgTools.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/RunConfigType.kt

Bug fix/quarkus tests do not use OTEL agent

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/MainToolWindowPanel.kt

Bug fix/bring back the quarkus pop-up

---

src/main/kotlin/org/digma/intellij/plugin/ui/list/insights/SpanPanelsUtil.kt

Partially fix #891 ( Endpoint Duration Slowdown Panel )

Bug fix/use span display name in link

---

src/main/java/org/digma/intellij/plugin/recentactivity/RecentActivityService.java

open browser from recent activity

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/posthog/ActivityMonitor.kt

Cache error hash to decrease error sending rate

---

src/main/java/org/digma/intellij/plugin/toolwindow/DigmaSidePaneToolWindowFactory.java

skip installation wizard event

skip installation wizard event

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaLanguageService.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JaxrsJakartaFramework.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JaxrsJavaxFramework.java

Feature/JAXRS - support both javax and jakarta

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt

fixes #1054 
now, part of the PR, it adds the following block (without versions):
```
implementation 'org.springframework.boot:spring-boot-starter-actuator'
implementation 'org.springframework.boot:spring-boot-starter-aop'
implementation 'io.micrometer:micrometer-tracing-bridge-otel'
implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
```

SpringBoot gradle - remove implicit version deps

---

src/main/kotlin/org/digma/intellij/plugin/ui/common/ProjectHomePanel.kt

Bug fix/add small gap at project panel

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/Constants.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaSpanDiscoveryUtils.java

addresses https://github.com/digma-ai/digma-collector-backend/issues/1054 sub task 4

Feature/support annotation WithSpan of OpenLiberty-MicroProfile

---

java/src/main/java/org/digma/intellij/plugin/idea/psi/java/AbsJaxrsFramework.java

address https://github.com/digma-ai/digma-collector-backend/issues/1054 sub task 3
respecting annotations `jakarta.ws.rs.ApplicationPath` and `javax.ws.rs.ApplicationPath` and it affects on discovery of endpoints.
hete's the outcome
1. here's the focused method:
2. the project has 2 define application scopes:
3. seeing insights for both 2 endpoints

Feature/JAX-RS endpoints - respect annotation ApplicationPath

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java
ide-common/src/main/kotlin/org/digma/intellij/plugin/common/EnvironmentUtil.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/QuarkusRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/RunConfigType.kt
src/main/java/org/digma/intellij/plugin/recentactivity/RecentActivityService.java
src/main/kotlin/org/digma/intellij/plugin/ui/common/EnvironmentsCombo.kt

fixes #1073 
using suffix of `[LOCAL-TEST]` similar as we have `[LOCAL]`
* see the drop down UI:
* Recent activity UI:

Feature/local tests environment - similar to LOCAL one

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OpenLibertyRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OtelRunConfigurationExtension.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/QuarkusRunConfigurationWrapper.kt
src/main/resources/META-INF/org.digma.intellij-with-java.xml

Feature/OpenLiberty RunConfiguration

---

ide-common/src/main/java/org/digma/intellij/plugin/common/StartupStartupActivity.java
src/main/resources/META-INF/plugin.xml

register the startup events earlier in dumb mode

Register startup events earlier

---

src/main/resources/webview/insights/index.js

Includes:
- https://github.com/digma-ai/digma-ui/pull/204

Update Insight UI

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/codelens/AbstractCodeLensService.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/ui/service/ErrorsViewService.kt
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/DocumentsChangeListenerForJavaSpanNavigation.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/EndpointDiscovery.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaEndpointNavigationProvider.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaSpanNavigationProvider.java
java/src/main/java/org/digma/intellij/plugin/idea/psi/java/JavaSpanNavigationStartupActivity.java
python/src/main/java/org/digma/intellij/plugin/psi/python/DocumentsChangeListenerForPythonSpanNavigation.java
python/src/main/java/org/digma/intellij/plugin/psi/python/PythonSpanNavigationProvider.java
python/src/main/java/org/digma/intellij/plugin/psi/python/PythonSpanNavigationStartupActivity.java

closes
https://github.com/digma-ai/digma-intellij-plugin/issues/1153

Minimize long running read access Closes #1153

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/QuarkusConfigureDepsService.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt
src/main/kotlin/org/digma/intellij/plugin/ui/frameworks/QuarkusConfigureDepsPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/frameworks/SpringBootMicrometerConfigureDepsPanel.kt

(cherry picked from commit ee8e78d68db0aff1fa6fa1913132c2c714aea259)

fix timer disposing and check project.isDisposed

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/QuarkusRunConfigurationWrapper.kt

still have problem with quarkus version 3.4.1
waiting for this fix:
https://github.com/quarkusio/quarkus/issues/29448#issuecomment-1747299321

Small fix/QuarkusTest - use duration values

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/EeAppServerAtIdeaUltimateRunConfigurationWrapper.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/OtelRunConfigurationExtension.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/RunConfigType.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/UltimateEeAppServerRunConfigurationWrapper.kt

fixes #1347 
now supporting the followinf 
WildFly ( JBoss )
TomEE
GlassFish
so now we support all 4 app servers (including Tomcat)

Feature/support EE Application Servers Run Configurations by IDEA Ultimate

---

src/main/resources/webview/documentation/index.js

Includes:
- https://github.com/digma-ai/digma-ui/pull/281

Update Documentation UI

---

src/main/java/org/digma/intellij/plugin/assets/AssetsService.java

Return empty assets array when no envs

---

java/src/main/kotlin/org/digma/intellij/plugin/idea/deps/ModulesDepsService.kt
java/src/main/kotlin/org/digma/intellij/plugin/idea/frameworks/SpringBootMicrometerConfigureDepsService.kt

fixes https://github.com/digma-ai/digma-collector-backend/issues/1380

Feature/spring boot micrometer - add dependency to DatasourceMicrometer

---

model/src/main/kotlin/org/digma/intellij/plugin/model/rest/insights/SpanNPlusEndpoints.kt

fixes issue: https://github.com/digma-ai/digma-intellij-plugin/issues/1504

add traceid and duration to spanNplusEndpoints

---

jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt

Feature/do not use OTEL agent when Micronaut module

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/persistence/PersistenceService.kt
ide-common/src/main/kotlin/org/digma/intellij/plugin/posthog/ActivityMonitor.kt
src/main/kotlin/org/digma/intellij/plugin/ui/jcef/RegistrationEventHandler.kt

https://github.com/digma-ai/digma-collector-backend/issues/1537

fixes backend issue ##1537

---

jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/deps/ModulesDepsService.kt
jvm-common/src/main/kotlin/org/digma/intellij/plugin/idea/runcfg/AutoOtelAgentRunConfigurationWrapper.kt

Feature/build Modules Metadata on the fly - in order to avoid race condition

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/navigation/MainContentViewSwitcher.kt

Rename Insights tab to Issues

---

src/main/kotlin/org/digma/intellij/plugin/ui/highlights/HighlightsMessageRouterHandler.kt

Refactor version comparison

---

ide-common/src/main/kotlin/org/digma/intellij/plugin/common/UniqueGeneratedUserId.kt
ide-common/src/test/kotlin/org/digma/intellij/plugin/common/UserIdTests.kt

https://github.com/digma-ai/digma-intellij-plugin/issues/2256

unique user id Closes #2256

---

ide-common/src/main/java/org/digma/intellij/plugin/editor/CurrentContextUpdater.java
ide-common/src/main/java/org/digma/intellij/plugin/editor/DocumentChangeListener.java
ide-common/src/main/java/org/digma/intellij/plugin/editor/EditorEventsHandler.java
src/main/kotlin/org/digma/intellij/plugin/ui/common/statuspanels/AggressiveUpdatePanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/frameworks/QuarkusConfigureDepsPanel.kt
src/main/kotlin/org/digma/intellij/plugin/ui/frameworks/SpringBootMicrometerConfigureDepsPanel.kt

https://github.com/digma-ai/digma-intellij-plugin/issues/2295

alarm-factory-deprecated Closes #2295

---

ide-common/src/main/java/org/digma/intellij/plugin/analytics/AnalyticsService.java
ide-common/src/main/java/org/digma/intellij/plugin/common/ExceptionUtils.java

better exception handling for methods that should not affect connecti… Closes #2416

---

ide-common/src/main/java/org/digma/intellij/plugin/document/CodeLensProvider.java

fixes https://github.com/digma-ai/digma-intellij-plugin/issues/2497

Fixed lens request

---

src/main/java/org/digma/intellij/plugin/dashboard/DashboardIndexTemplateBuilder.java

Fix report

---

src/main/java/org/digma/intellij/plugin/toolwindow/DigmaSidePaneToolWindowFactory.java
src/main/kotlin/org/digma/intellij/plugin/ui/common/JcefRemoteUtils.kt
src/main/kotlin/org/digma/intellij/plugin/ui/recentactivity/RecentActivityToolWindowFactory.kt

(cherry picked from commit c41b170c2a870189938910c0c382dca4367e48bb)

show jcef workaround message
